<?php


/**
 * This class adds structure of 'utilisateur' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/26/15 10:56:57
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UtilisateurMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UtilisateurMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UtilisateurPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UtilisateurPeer::TABLE_NAME);
		$tMap->setPhpName('Utilisateur');
		$tMap->setClassname('Utilisateur');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'BIGINT', true, 20);

		$tMap->addColumn('PSEUDO', 'Pseudo', 'VARCHAR', true, 25);

		$tMap->addColumn('PWD', 'Pwd', 'VARCHAR', true, 40);

		$tMap->addColumn('DATECREATE', 'Datecreate', 'TIMESTAMP', true, null);

		$tMap->addColumn('MAIL', 'Mail', 'VARCHAR', false, 100);

		$tMap->addColumn('DATELASTCONN', 'Datelastconn', 'TIMESTAMP', false, null);

	} // doBuild()

} // UtilisateurMapBuilder
