<?php

/**
 * Base class that represents a row from the 'utilisateur' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 09/09/15 10:08:30
 *
 * @package    lib.model.om
 */
abstract class BaseUtilisateur extends BaseObject  implements Persistent {


  const PEER = 'UtilisateurPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UtilisateurPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the pseudo field.
	 * @var        string
	 */
	protected $pseudo;

	/**
	 * The value for the pwd field.
	 * @var        string
	 */
	protected $pwd;

	/**
	 * The value for the datecreate field.
	 * @var        string
	 */
	protected $datecreate;

	/**
	 * The value for the mail field.
	 * @var        string
	 */
	protected $mail;

	/**
	 * The value for the datelastconn field.
	 * @var        string
	 */
	protected $datelastconn;

	/**
	 * @var        array Categorie[] Collection to store aggregation of Categorie objects.
	 */
	protected $collCategories;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCategories.
	 */
	private $lastCategorieCriteria = null;

	/**
	 * @var        array Liste[] Collection to store aggregation of Liste objects.
	 */
	protected $collListes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collListes.
	 */
	private $lastListeCriteria = null;

	/**
	 * @var        array ListeProduitLink[] Collection to store aggregation of ListeProduitLink objects.
	 */
	protected $collListeProduitLinks;

	/**
	 * @var        Criteria The criteria used to select the current contents of collListeProduitLinks.
	 */
	private $lastListeProduitLinkCriteria = null;

	/**
	 * @var        array Magasin[] Collection to store aggregation of Magasin objects.
	 */
	protected $collMagasins;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMagasins.
	 */
	private $lastMagasinCriteria = null;

	/**
	 * @var        array MagasinsFavoris[] Collection to store aggregation of MagasinsFavoris objects.
	 */
	protected $collMagasinsFavoriss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMagasinsFavoriss.
	 */
	private $lastMagasinsFavorisCriteria = null;

	/**
	 * @var        array Produit[] Collection to store aggregation of Produit objects.
	 */
	protected $collProduits;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProduits.
	 */
	private $lastProduitCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUtilisateur object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [pseudo] column value.
	 * 
	 * @return     string
	 */
	public function getPseudo()
	{
		return $this->pseudo;
	}

	/**
	 * Get the [pwd] column value.
	 * 
	 * @return     string
	 */
	public function getPwd()
	{
		return $this->pwd;
	}

	/**
	 * Get the [optionally formatted] temporal [datecreate] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDatecreate($format = 'Y-m-d H:i:s')
	{
		if ($this->datecreate === null) {
			return null;
		}


		if ($this->datecreate === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->datecreate);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->datecreate, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [mail] column value.
	 * 
	 * @return     string
	 */
	public function getMail()
	{
		return $this->mail;
	}

	/**
	 * Get the [optionally formatted] temporal [datelastconn] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDatelastconn($format = 'Y-m-d H:i:s')
	{
		if ($this->datelastconn === null) {
			return null;
		}


		if ($this->datelastconn === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->datelastconn);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->datelastconn, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     Utilisateur The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = UtilisateurPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [pseudo] column.
	 * 
	 * @param      string $v new value
	 * @return     Utilisateur The current object (for fluent API support)
	 */
	public function setPseudo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pseudo !== $v) {
			$this->pseudo = $v;
			$this->modifiedColumns[] = UtilisateurPeer::PSEUDO;
		}

		return $this;
	} // setPseudo()

	/**
	 * Set the value of [pwd] column.
	 * 
	 * @param      string $v new value
	 * @return     Utilisateur The current object (for fluent API support)
	 */
	public function setPwd($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pwd !== $v) {
			$this->pwd = $v;
			$this->modifiedColumns[] = UtilisateurPeer::PWD;
		}

		return $this;
	} // setPwd()

	/**
	 * Sets the value of [datecreate] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Utilisateur The current object (for fluent API support)
	 */
	public function setDatecreate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->datecreate !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->datecreate !== null && $tmpDt = new DateTime($this->datecreate)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->datecreate = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UtilisateurPeer::DATECREATE;
			}
		} // if either are not null

		return $this;
	} // setDatecreate()

	/**
	 * Set the value of [mail] column.
	 * 
	 * @param      string $v new value
	 * @return     Utilisateur The current object (for fluent API support)
	 */
	public function setMail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mail !== $v) {
			$this->mail = $v;
			$this->modifiedColumns[] = UtilisateurPeer::MAIL;
		}

		return $this;
	} // setMail()

	/**
	 * Sets the value of [datelastconn] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Utilisateur The current object (for fluent API support)
	 */
	public function setDatelastconn($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->datelastconn !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->datelastconn !== null && $tmpDt = new DateTime($this->datelastconn)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->datelastconn = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UtilisateurPeer::DATELASTCONN;
			}
		} // if either are not null

		return $this;
	} // setDatelastconn()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->pseudo = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->pwd = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->datecreate = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->mail = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->datelastconn = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = UtilisateurPeer::NUM_COLUMNS - UtilisateurPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Utilisateur object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UtilisateurPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UtilisateurPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collCategories = null;
			$this->lastCategorieCriteria = null;

			$this->collListes = null;
			$this->lastListeCriteria = null;

			$this->collListeProduitLinks = null;
			$this->lastListeProduitLinkCriteria = null;

			$this->collMagasins = null;
			$this->lastMagasinCriteria = null;

			$this->collMagasinsFavoriss = null;
			$this->lastMagasinsFavorisCriteria = null;

			$this->collProduits = null;
			$this->lastProduitCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUtilisateur:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UtilisateurPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UtilisateurPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUtilisateur:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUtilisateur:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UtilisateurPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUtilisateur:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UtilisateurPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UtilisateurPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UtilisateurPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UtilisateurPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCategories !== null) {
				foreach ($this->collCategories as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collListes !== null) {
				foreach ($this->collListes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collListeProduitLinks !== null) {
				foreach ($this->collListeProduitLinks as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMagasins !== null) {
				foreach ($this->collMagasins as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMagasinsFavoriss !== null) {
				foreach ($this->collMagasinsFavoriss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collProduits !== null) {
				foreach ($this->collProduits as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = UtilisateurPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCategories !== null) {
					foreach ($this->collCategories as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collListes !== null) {
					foreach ($this->collListes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collListeProduitLinks !== null) {
					foreach ($this->collListeProduitLinks as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMagasins !== null) {
					foreach ($this->collMagasins as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMagasinsFavoriss !== null) {
					foreach ($this->collMagasinsFavoriss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collProduits !== null) {
					foreach ($this->collProduits as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UtilisateurPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPseudo();
				break;
			case 2:
				return $this->getPwd();
				break;
			case 3:
				return $this->getDatecreate();
				break;
			case 4:
				return $this->getMail();
				break;
			case 5:
				return $this->getDatelastconn();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UtilisateurPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPseudo(),
			$keys[2] => $this->getPwd(),
			$keys[3] => $this->getDatecreate(),
			$keys[4] => $this->getMail(),
			$keys[5] => $this->getDatelastconn(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UtilisateurPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPseudo($value);
				break;
			case 2:
				$this->setPwd($value);
				break;
			case 3:
				$this->setDatecreate($value);
				break;
			case 4:
				$this->setMail($value);
				break;
			case 5:
				$this->setDatelastconn($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UtilisateurPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPseudo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPwd($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDatecreate($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setMail($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDatelastconn($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);

		if ($this->isColumnModified(UtilisateurPeer::ID)) $criteria->add(UtilisateurPeer::ID, $this->id);
		if ($this->isColumnModified(UtilisateurPeer::PSEUDO)) $criteria->add(UtilisateurPeer::PSEUDO, $this->pseudo);
		if ($this->isColumnModified(UtilisateurPeer::PWD)) $criteria->add(UtilisateurPeer::PWD, $this->pwd);
		if ($this->isColumnModified(UtilisateurPeer::DATECREATE)) $criteria->add(UtilisateurPeer::DATECREATE, $this->datecreate);
		if ($this->isColumnModified(UtilisateurPeer::MAIL)) $criteria->add(UtilisateurPeer::MAIL, $this->mail);
		if ($this->isColumnModified(UtilisateurPeer::DATELASTCONN)) $criteria->add(UtilisateurPeer::DATELASTCONN, $this->datelastconn);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);

		$criteria->add(UtilisateurPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Utilisateur (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPseudo($this->pseudo);

		$copyObj->setPwd($this->pwd);

		$copyObj->setDatecreate($this->datecreate);

		$copyObj->setMail($this->mail);

		$copyObj->setDatelastconn($this->datelastconn);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCategories() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCategorie($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getListes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addListe($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getListeProduitLinks() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addListeProduitLink($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMagasins() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMagasin($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMagasinsFavoriss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMagasinsFavoris($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getProduits() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProduit($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Utilisateur Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UtilisateurPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UtilisateurPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collCategories collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCategories()
	 */
	public function clearCategories()
	{
		$this->collCategories = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCategories collection (array).
	 *
	 * By default this just sets the collCategories collection to an empty array (like clearcollCategories());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCategories()
	{
		$this->collCategories = array();
	}

	/**
	 * Gets an array of Categorie objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Utilisateur has previously been saved, it will retrieve
	 * related Categories from storage. If this Utilisateur is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Categorie[]
	 * @throws     PropelException
	 */
	public function getCategories($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCategories === null) {
			if ($this->isNew()) {
			   $this->collCategories = array();
			} else {

				$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

				CategoriePeer::addSelectColumns($criteria);
				$this->collCategories = CategoriePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

				CategoriePeer::addSelectColumns($criteria);
				if (!isset($this->lastCategorieCriteria) || !$this->lastCategorieCriteria->equals($criteria)) {
					$this->collCategories = CategoriePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCategorieCriteria = $criteria;
		return $this->collCategories;
	}

	/**
	 * Returns the number of related Categorie objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Categorie objects.
	 * @throws     PropelException
	 */
	public function countCategories(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCategories === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

				$count = CategoriePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

				if (!isset($this->lastCategorieCriteria) || !$this->lastCategorieCriteria->equals($criteria)) {
					$count = CategoriePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCategories);
				}
			} else {
				$count = count($this->collCategories);
			}
		}
		$this->lastCategorieCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Categorie object to this object
	 * through the Categorie foreign key attribute.
	 *
	 * @param      Categorie $l Categorie
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCategorie(Categorie $l)
	{
		if ($this->collCategories === null) {
			$this->initCategories();
		}
		if (!in_array($l, $this->collCategories, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCategories, $l);
			$l->setUtilisateur($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Categories from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getCategoriesJoinCategorieRelatedByIdParent($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCategories === null) {
			if ($this->isNew()) {
				$this->collCategories = array();
			} else {

				$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

				$this->collCategories = CategoriePeer::doSelectJoinCategorieRelatedByIdParent($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastCategorieCriteria) || !$this->lastCategorieCriteria->equals($criteria)) {
				$this->collCategories = CategoriePeer::doSelectJoinCategorieRelatedByIdParent($criteria, $con, $join_behavior);
			}
		}
		$this->lastCategorieCriteria = $criteria;

		return $this->collCategories;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Categories from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getCategoriesJoinEtat($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCategories === null) {
			if ($this->isNew()) {
				$this->collCategories = array();
			} else {

				$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

				$this->collCategories = CategoriePeer::doSelectJoinEtat($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastCategorieCriteria) || !$this->lastCategorieCriteria->equals($criteria)) {
				$this->collCategories = CategoriePeer::doSelectJoinEtat($criteria, $con, $join_behavior);
			}
		}
		$this->lastCategorieCriteria = $criteria;

		return $this->collCategories;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Categories from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getCategoriesJoinVisibilite($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCategories === null) {
			if ($this->isNew()) {
				$this->collCategories = array();
			} else {

				$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

				$this->collCategories = CategoriePeer::doSelectJoinVisibilite($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CategoriePeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastCategorieCriteria) || !$this->lastCategorieCriteria->equals($criteria)) {
				$this->collCategories = CategoriePeer::doSelectJoinVisibilite($criteria, $con, $join_behavior);
			}
		}
		$this->lastCategorieCriteria = $criteria;

		return $this->collCategories;
	}

	/**
	 * Clears out the collListes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addListes()
	 */
	public function clearListes()
	{
		$this->collListes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collListes collection (array).
	 *
	 * By default this just sets the collListes collection to an empty array (like clearcollListes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initListes()
	{
		$this->collListes = array();
	}

	/**
	 * Gets an array of Liste objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Utilisateur has previously been saved, it will retrieve
	 * related Listes from storage. If this Utilisateur is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Liste[]
	 * @throws     PropelException
	 */
	public function getListes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListes === null) {
			if ($this->isNew()) {
			   $this->collListes = array();
			} else {

				$criteria->add(ListePeer::ID_UTILISATEUR, $this->id);

				ListePeer::addSelectColumns($criteria);
				$this->collListes = ListePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ListePeer::ID_UTILISATEUR, $this->id);

				ListePeer::addSelectColumns($criteria);
				if (!isset($this->lastListeCriteria) || !$this->lastListeCriteria->equals($criteria)) {
					$this->collListes = ListePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastListeCriteria = $criteria;
		return $this->collListes;
	}

	/**
	 * Returns the number of related Liste objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Liste objects.
	 * @throws     PropelException
	 */
	public function countListes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collListes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ListePeer::ID_UTILISATEUR, $this->id);

				$count = ListePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ListePeer::ID_UTILISATEUR, $this->id);

				if (!isset($this->lastListeCriteria) || !$this->lastListeCriteria->equals($criteria)) {
					$count = ListePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collListes);
				}
			} else {
				$count = count($this->collListes);
			}
		}
		$this->lastListeCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Liste object to this object
	 * through the Liste foreign key attribute.
	 *
	 * @param      Liste $l Liste
	 * @return     void
	 * @throws     PropelException
	 */
	public function addListe(Liste $l)
	{
		if ($this->collListes === null) {
			$this->initListes();
		}
		if (!in_array($l, $this->collListes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collListes, $l);
			$l->setUtilisateur($this);
		}
	}

	/**
	 * Clears out the collListeProduitLinks collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addListeProduitLinks()
	 */
	public function clearListeProduitLinks()
	{
		$this->collListeProduitLinks = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collListeProduitLinks collection (array).
	 *
	 * By default this just sets the collListeProduitLinks collection to an empty array (like clearcollListeProduitLinks());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initListeProduitLinks()
	{
		$this->collListeProduitLinks = array();
	}

	/**
	 * Gets an array of ListeProduitLink objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Utilisateur has previously been saved, it will retrieve
	 * related ListeProduitLinks from storage. If this Utilisateur is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ListeProduitLink[]
	 * @throws     PropelException
	 */
	public function getListeProduitLinks($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListeProduitLinks === null) {
			if ($this->isNew()) {
			   $this->collListeProduitLinks = array();
			} else {

				$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

				ListeProduitLinkPeer::addSelectColumns($criteria);
				$this->collListeProduitLinks = ListeProduitLinkPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

				ListeProduitLinkPeer::addSelectColumns($criteria);
				if (!isset($this->lastListeProduitLinkCriteria) || !$this->lastListeProduitLinkCriteria->equals($criteria)) {
					$this->collListeProduitLinks = ListeProduitLinkPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastListeProduitLinkCriteria = $criteria;
		return $this->collListeProduitLinks;
	}

	/**
	 * Returns the number of related ListeProduitLink objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ListeProduitLink objects.
	 * @throws     PropelException
	 */
	public function countListeProduitLinks(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collListeProduitLinks === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

				$count = ListeProduitLinkPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

				if (!isset($this->lastListeProduitLinkCriteria) || !$this->lastListeProduitLinkCriteria->equals($criteria)) {
					$count = ListeProduitLinkPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collListeProduitLinks);
				}
			} else {
				$count = count($this->collListeProduitLinks);
			}
		}
		$this->lastListeProduitLinkCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a ListeProduitLink object to this object
	 * through the ListeProduitLink foreign key attribute.
	 *
	 * @param      ListeProduitLink $l ListeProduitLink
	 * @return     void
	 * @throws     PropelException
	 */
	public function addListeProduitLink(ListeProduitLink $l)
	{
		if ($this->collListeProduitLinks === null) {
			$this->initListeProduitLinks();
		}
		if (!in_array($l, $this->collListeProduitLinks, true)) { // only add it if the **same** object is not already associated
			array_push($this->collListeProduitLinks, $l);
			$l->setUtilisateur($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related ListeProduitLinks from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getListeProduitLinksJoinListe($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListeProduitLinks === null) {
			if ($this->isNew()) {
				$this->collListeProduitLinks = array();
			} else {

				$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

				$this->collListeProduitLinks = ListeProduitLinkPeer::doSelectJoinListe($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

			if (!isset($this->lastListeProduitLinkCriteria) || !$this->lastListeProduitLinkCriteria->equals($criteria)) {
				$this->collListeProduitLinks = ListeProduitLinkPeer::doSelectJoinListe($criteria, $con, $join_behavior);
			}
		}
		$this->lastListeProduitLinkCriteria = $criteria;

		return $this->collListeProduitLinks;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related ListeProduitLinks from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getListeProduitLinksJoinProduit($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListeProduitLinks === null) {
			if ($this->isNew()) {
				$this->collListeProduitLinks = array();
			} else {

				$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

				$this->collListeProduitLinks = ListeProduitLinkPeer::doSelectJoinProduit($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

			if (!isset($this->lastListeProduitLinkCriteria) || !$this->lastListeProduitLinkCriteria->equals($criteria)) {
				$this->collListeProduitLinks = ListeProduitLinkPeer::doSelectJoinProduit($criteria, $con, $join_behavior);
			}
		}
		$this->lastListeProduitLinkCriteria = $criteria;

		return $this->collListeProduitLinks;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related ListeProduitLinks from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getListeProduitLinksJoinMagasin($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListeProduitLinks === null) {
			if ($this->isNew()) {
				$this->collListeProduitLinks = array();
			} else {

				$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

				$this->collListeProduitLinks = ListeProduitLinkPeer::doSelectJoinMagasin($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ListeProduitLinkPeer::COCHE_ID_UTILISTEUR, $this->id);

			if (!isset($this->lastListeProduitLinkCriteria) || !$this->lastListeProduitLinkCriteria->equals($criteria)) {
				$this->collListeProduitLinks = ListeProduitLinkPeer::doSelectJoinMagasin($criteria, $con, $join_behavior);
			}
		}
		$this->lastListeProduitLinkCriteria = $criteria;

		return $this->collListeProduitLinks;
	}

	/**
	 * Clears out the collMagasins collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMagasins()
	 */
	public function clearMagasins()
	{
		$this->collMagasins = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMagasins collection (array).
	 *
	 * By default this just sets the collMagasins collection to an empty array (like clearcollMagasins());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMagasins()
	{
		$this->collMagasins = array();
	}

	/**
	 * Gets an array of Magasin objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Utilisateur has previously been saved, it will retrieve
	 * related Magasins from storage. If this Utilisateur is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Magasin[]
	 * @throws     PropelException
	 */
	public function getMagasins($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMagasins === null) {
			if ($this->isNew()) {
			   $this->collMagasins = array();
			} else {

				$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

				MagasinPeer::addSelectColumns($criteria);
				$this->collMagasins = MagasinPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

				MagasinPeer::addSelectColumns($criteria);
				if (!isset($this->lastMagasinCriteria) || !$this->lastMagasinCriteria->equals($criteria)) {
					$this->collMagasins = MagasinPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMagasinCriteria = $criteria;
		return $this->collMagasins;
	}

	/**
	 * Returns the number of related Magasin objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Magasin objects.
	 * @throws     PropelException
	 */
	public function countMagasins(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMagasins === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

				$count = MagasinPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

				if (!isset($this->lastMagasinCriteria) || !$this->lastMagasinCriteria->equals($criteria)) {
					$count = MagasinPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMagasins);
				}
			} else {
				$count = count($this->collMagasins);
			}
		}
		$this->lastMagasinCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Magasin object to this object
	 * through the Magasin foreign key attribute.
	 *
	 * @param      Magasin $l Magasin
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMagasin(Magasin $l)
	{
		if ($this->collMagasins === null) {
			$this->initMagasins();
		}
		if (!in_array($l, $this->collMagasins, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMagasins, $l);
			$l->setUtilisateur($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Magasins from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getMagasinsJoinVisibilite($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMagasins === null) {
			if ($this->isNew()) {
				$this->collMagasins = array();
			} else {

				$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

				$this->collMagasins = MagasinPeer::doSelectJoinVisibilite($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastMagasinCriteria) || !$this->lastMagasinCriteria->equals($criteria)) {
				$this->collMagasins = MagasinPeer::doSelectJoinVisibilite($criteria, $con, $join_behavior);
			}
		}
		$this->lastMagasinCriteria = $criteria;

		return $this->collMagasins;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Magasins from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getMagasinsJoinEtat($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMagasins === null) {
			if ($this->isNew()) {
				$this->collMagasins = array();
			} else {

				$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

				$this->collMagasins = MagasinPeer::doSelectJoinEtat($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MagasinPeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastMagasinCriteria) || !$this->lastMagasinCriteria->equals($criteria)) {
				$this->collMagasins = MagasinPeer::doSelectJoinEtat($criteria, $con, $join_behavior);
			}
		}
		$this->lastMagasinCriteria = $criteria;

		return $this->collMagasins;
	}

	/**
	 * Clears out the collMagasinsFavoriss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMagasinsFavoriss()
	 */
	public function clearMagasinsFavoriss()
	{
		$this->collMagasinsFavoriss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMagasinsFavoriss collection (array).
	 *
	 * By default this just sets the collMagasinsFavoriss collection to an empty array (like clearcollMagasinsFavoriss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMagasinsFavoriss()
	{
		$this->collMagasinsFavoriss = array();
	}

	/**
	 * Gets an array of MagasinsFavoris objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Utilisateur has previously been saved, it will retrieve
	 * related MagasinsFavoriss from storage. If this Utilisateur is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MagasinsFavoris[]
	 * @throws     PropelException
	 */
	public function getMagasinsFavoriss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMagasinsFavoriss === null) {
			if ($this->isNew()) {
			   $this->collMagasinsFavoriss = array();
			} else {

				$criteria->add(MagasinsFavorisPeer::ID_UTILISATEUR, $this->id);

				MagasinsFavorisPeer::addSelectColumns($criteria);
				$this->collMagasinsFavoriss = MagasinsFavorisPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MagasinsFavorisPeer::ID_UTILISATEUR, $this->id);

				MagasinsFavorisPeer::addSelectColumns($criteria);
				if (!isset($this->lastMagasinsFavorisCriteria) || !$this->lastMagasinsFavorisCriteria->equals($criteria)) {
					$this->collMagasinsFavoriss = MagasinsFavorisPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMagasinsFavorisCriteria = $criteria;
		return $this->collMagasinsFavoriss;
	}

	/**
	 * Returns the number of related MagasinsFavoris objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MagasinsFavoris objects.
	 * @throws     PropelException
	 */
	public function countMagasinsFavoriss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMagasinsFavoriss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MagasinsFavorisPeer::ID_UTILISATEUR, $this->id);

				$count = MagasinsFavorisPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MagasinsFavorisPeer::ID_UTILISATEUR, $this->id);

				if (!isset($this->lastMagasinsFavorisCriteria) || !$this->lastMagasinsFavorisCriteria->equals($criteria)) {
					$count = MagasinsFavorisPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMagasinsFavoriss);
				}
			} else {
				$count = count($this->collMagasinsFavoriss);
			}
		}
		$this->lastMagasinsFavorisCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a MagasinsFavoris object to this object
	 * through the MagasinsFavoris foreign key attribute.
	 *
	 * @param      MagasinsFavoris $l MagasinsFavoris
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMagasinsFavoris(MagasinsFavoris $l)
	{
		if ($this->collMagasinsFavoriss === null) {
			$this->initMagasinsFavoriss();
		}
		if (!in_array($l, $this->collMagasinsFavoriss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMagasinsFavoriss, $l);
			$l->setUtilisateur($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related MagasinsFavoriss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getMagasinsFavorissJoinMagasin($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMagasinsFavoriss === null) {
			if ($this->isNew()) {
				$this->collMagasinsFavoriss = array();
			} else {

				$criteria->add(MagasinsFavorisPeer::ID_UTILISATEUR, $this->id);

				$this->collMagasinsFavoriss = MagasinsFavorisPeer::doSelectJoinMagasin($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MagasinsFavorisPeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastMagasinsFavorisCriteria) || !$this->lastMagasinsFavorisCriteria->equals($criteria)) {
				$this->collMagasinsFavoriss = MagasinsFavorisPeer::doSelectJoinMagasin($criteria, $con, $join_behavior);
			}
		}
		$this->lastMagasinsFavorisCriteria = $criteria;

		return $this->collMagasinsFavoriss;
	}

	/**
	 * Clears out the collProduits collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProduits()
	 */
	public function clearProduits()
	{
		$this->collProduits = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProduits collection (array).
	 *
	 * By default this just sets the collProduits collection to an empty array (like clearcollProduits());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProduits()
	{
		$this->collProduits = array();
	}

	/**
	 * Gets an array of Produit objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Utilisateur has previously been saved, it will retrieve
	 * related Produits from storage. If this Utilisateur is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Produit[]
	 * @throws     PropelException
	 */
	public function getProduits($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProduits === null) {
			if ($this->isNew()) {
			   $this->collProduits = array();
			} else {

				$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

				ProduitPeer::addSelectColumns($criteria);
				$this->collProduits = ProduitPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

				ProduitPeer::addSelectColumns($criteria);
				if (!isset($this->lastProduitCriteria) || !$this->lastProduitCriteria->equals($criteria)) {
					$this->collProduits = ProduitPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProduitCriteria = $criteria;
		return $this->collProduits;
	}

	/**
	 * Returns the number of related Produit objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Produit objects.
	 * @throws     PropelException
	 */
	public function countProduits(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProduits === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

				$count = ProduitPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

				if (!isset($this->lastProduitCriteria) || !$this->lastProduitCriteria->equals($criteria)) {
					$count = ProduitPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProduits);
				}
			} else {
				$count = count($this->collProduits);
			}
		}
		$this->lastProduitCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Produit object to this object
	 * through the Produit foreign key attribute.
	 *
	 * @param      Produit $l Produit
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProduit(Produit $l)
	{
		if ($this->collProduits === null) {
			$this->initProduits();
		}
		if (!in_array($l, $this->collProduits, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProduits, $l);
			$l->setUtilisateur($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Produits from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getProduitsJoinCategorie($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProduits === null) {
			if ($this->isNew()) {
				$this->collProduits = array();
			} else {

				$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

				$this->collProduits = ProduitPeer::doSelectJoinCategorie($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastProduitCriteria) || !$this->lastProduitCriteria->equals($criteria)) {
				$this->collProduits = ProduitPeer::doSelectJoinCategorie($criteria, $con, $join_behavior);
			}
		}
		$this->lastProduitCriteria = $criteria;

		return $this->collProduits;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Produits from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getProduitsJoinEtat($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProduits === null) {
			if ($this->isNew()) {
				$this->collProduits = array();
			} else {

				$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

				$this->collProduits = ProduitPeer::doSelectJoinEtat($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastProduitCriteria) || !$this->lastProduitCriteria->equals($criteria)) {
				$this->collProduits = ProduitPeer::doSelectJoinEtat($criteria, $con, $join_behavior);
			}
		}
		$this->lastProduitCriteria = $criteria;

		return $this->collProduits;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Utilisateur is new, it will return
	 * an empty collection; or if this Utilisateur has previously
	 * been saved, it will retrieve related Produits from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Utilisateur.
	 */
	public function getProduitsJoinVisibilite($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UtilisateurPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProduits === null) {
			if ($this->isNew()) {
				$this->collProduits = array();
			} else {

				$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

				$this->collProduits = ProduitPeer::doSelectJoinVisibilite($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProduitPeer::ID_UTILISATEUR, $this->id);

			if (!isset($this->lastProduitCriteria) || !$this->lastProduitCriteria->equals($criteria)) {
				$this->collProduits = ProduitPeer::doSelectJoinVisibilite($criteria, $con, $join_behavior);
			}
		}
		$this->lastProduitCriteria = $criteria;

		return $this->collProduits;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCategories) {
				foreach ((array) $this->collCategories as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collListes) {
				foreach ((array) $this->collListes as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collListeProduitLinks) {
				foreach ((array) $this->collListeProduitLinks as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMagasins) {
				foreach ((array) $this->collMagasins as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMagasinsFavoriss) {
				foreach ((array) $this->collMagasinsFavoriss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collProduits) {
				foreach ((array) $this->collProduits as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCategories = null;
		$this->collListes = null;
		$this->collListeProduitLinks = null;
		$this->collMagasins = null;
		$this->collMagasinsFavoriss = null;
		$this->collProduits = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUtilisateur:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUtilisateur::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUtilisateur
