-- MySQL Script generated by MySQL Workbench
-- 05/29/15 09:53:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartlist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartlist` ;

-- -----------------------------------------------------
-- Schema smartlist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartlist` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `smartlist` ;

-- -----------------------------------------------------
-- Table `smartlist`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`categorie` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`categorie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(128) NOT NULL,
  `id_parent` INT(11) NULL DEFAULT NULL,
  `img` TEXT NULL DEFAULT NULL,
  `id_utilisateur` INT(11) NULL DEFAULT NULL,
  `id_etat` TINYINT(4) NOT NULL DEFAULT '1',
  `id_visibilité` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartlist`.`etat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`etat` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`etat` (
  `id` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NOT NULL,
  `nom` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartlist`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`utilisateur` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(25) NOT NULL,
  `pwd` VARCHAR(40) NOT NULL,
  `datecreate` DATETIME NOT NULL,
  `mail` VARCHAR(100) NULL DEFAULT NULL,
  `datelastconn` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartlist`.`liste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`liste` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`liste` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `id_utilisateur` BIGINT(20) NOT NULL,
  `id_partage` BLOB NULL DEFAULT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_modification` DATETIME NULL,
  INDEX `id_utilisateur_idx` (`id_utilisateur` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `smartlist`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartlist`.`visibilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`visibilite` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`visibilite` (
  `id` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NOT NULL,
  `nom` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartlist`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`produit` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`produit` (
  `id` BIGINT(20) NOT NULL,
  `nom` VARCHAR(128) NOT NULL,
  `img` TEXT NULL DEFAULT NULL COMMENT 'lien vers l\'image',
  `id_utilisateur` BIGINT(20) NULL DEFAULT NULL,
  `id_categorie` INT(11) NULL DEFAULT NULL,
  `id_etat` TINYINT(4) NOT NULL DEFAULT '1',
  `id_visibilite` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'visible par qui',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_etat_idx` (`id_etat` ASC),
  INDEX `fk_produit_utilisateur1_idx` (`id_utilisateur` ASC),
  INDEX `fk_produit_categorie1_idx` (`id_categorie` ASC),
  INDEX `fk_produit_visibilite_idx` (`id_visibilite` ASC),
  CONSTRAINT `fk_produit_etat`
    FOREIGN KEY (`id_etat`)
    REFERENCES `smartlist`.`etat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `smartlist`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_categorie1`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `smartlist`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_visibilite`
    FOREIGN KEY (`id_visibilite`)
    REFERENCES `smartlist`.`visibilite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartlist`.`magasin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`magasin` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`magasin` (
  `id` BIGINT(20) NOT NULL,
  `nom` VARCHAR(128) NOT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlist`.`liste_produit_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`liste_produit_link` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`liste_produit_link` (
  `id` BIGINT(20) NOT NULL,
  `id_liste` BIGINT(20) NOT NULL,
  `id_produit` BIGINT(20) NOT NULL,
  `quantite` INT NULL,
  `id_magazin` BIGINT(20) NULL DEFAULT NULL,
  `coche` TINYINT(1) NOT NULL DEFAULT 0,
  `coche_date` DATETIME NULL DEFAULT NULL,
  `coche_id_utilisteur` BIGINT(20) NOT NULL,
  INDEX `fk_lpl_magasin_idx` (`id_magazin` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_lpl_utilisateur_idx` (`coche_id_utilisteur` ASC),
  INDEX `fk_lpl_produit_idx` (`id_produit` ASC),
  INDEX `fk_lpl_liste_idx` (`id_liste` ASC),
  CONSTRAINT `fk_lpl_liste`
    FOREIGN KEY (`id_liste`)
    REFERENCES `smartlist`.`liste` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lpl_produit`
    FOREIGN KEY (`id_produit`)
    REFERENCES `smartlist`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lpl_magasin`
    FOREIGN KEY (`id_magazin`)
    REFERENCES `smartlist`.`magasin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lpl_utilisateur`
    FOREIGN KEY (`coche_id_utilisteur`)
    REFERENCES `smartlist`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `smartlist`.`utilisateur_liste_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`utilisateur_liste_link` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`utilisateur_liste_link` (
  `id` BIGINT(20) NOT NULL,
  `id_liste` BIGINT(20) NOT NULL,
  `id_utilisateur` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_partage_utilisateur1_idx` (`id_utilisateur` ASC),
  INDEX `fk_partage_liste1_idx` (`id_liste` ASC),
  CONSTRAINT `fk_partage_liste1`
    FOREIGN KEY (`id_liste`)
    REFERENCES `smartlist`.`liste` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partage_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `smartlist`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `smartlist`.`etat`
-- -----------------------------------------------------
START TRANSACTION;
USE `smartlist`;
INSERT INTO `smartlist`.`etat` (`id`, `code`, `nom`) VALUES (DEFAULT, 'VAL', 'Validé');
INSERT INTO `smartlist`.`etat` (`id`, `code`, `nom`) VALUES (DEFAULT, 'ATT', 'En attente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `smartlist`.`visibilite`
-- -----------------------------------------------------
START TRANSACTION;
USE `smartlist`;
INSERT INTO `smartlist`.`visibilite` (`id`, `code`, `nom`) VALUES (DEFAULT, 'MOI', 'Perso');
INSERT INTO `smartlist`.`visibilite` (`id`, `code`, `nom`) VALUES (DEFAULT, 'LST', 'Liste');
INSERT INTO `smartlist`.`visibilite` (`id`, `code`, `nom`) VALUES (DEFAULT, 'SIT', 'Site');

COMMIT;

