default:
  http_metas:
    content-type: text/html

  metas:
    title:        SmartListe
    description:  Ma liste de course partagée
    keywords:     SmartListe, liste, course
    language:     fr
    #robots:       index, follow
    charset:      UTF-8
    
  stylesheets:    [bootstrap.min.css, bootstrap-theme.min.css, font-awesome.min.css, jquery.simplecolorpicker.css, nico.css, max.css]

  javascripts:    [jquery-1.11.2.js, bootstrap.min.js, jquery.simplecolorpicker.js, max.js, nico.js]

  has_layout:     true
  layout:         layout
