<?php
// auto-generated by sfViewConfigHandler
// date: 2015/05/29 11:26:36
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'SmartListe : ma liste de course partagée', false, false);
  $response->addMeta('language', 'fr', false, false);
  $response->addMeta('charset', 'UTF-8', false, false);

  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('bootstrap-theme.min.css', '', array ());
  $response->addStylesheet('nico.css', '', array ());
  $response->addStylesheet('max.css', '', array ());
  $response->addJavascript('jquery-1.11.2.js', '', array ());
  $response->addJavascript('bootstrap.min.js', '', array ());
  $response->addJavascript('max.js', '', array ());
  $response->addJavascript('nico.js', '', array ());


